irc:
    server: irc.libera.chat
    port: 6667
    ssl: false
    nick: clymene-test
    channel: "#dolphin-test"
    ignore_users:
        - "irrawaddy-test"

discord:
    token: "token"
    channel: 1234
    ignore_users:
        - 1234